#!/usr/bin/env python3
"""Rebuild questions/data.js from questions/data.json.

Reads the consolidated JSON data file and generates a JavaScript file
containing the EMBEDDED_DATA array used by the flashcards application.

Usage:
    python3 rebuild.py [--dry-run]
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_JSON = ROOT / "questions" / "data.json"
DATA_JS = ROOT / "questions" / "data.js"


def load_topics(path: Path) -> list[dict]:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data


def build_js(topics: list[dict]) -> str:
    lines = [
        "// Auto-generated by rebuild.py — do not edit manually",
        "const EMBEDDED_DATA = [",
    ]
    for entry in topics:
        q_json = json.dumps(entry["q"], ensure_ascii=False)
        a_json = json.dumps(entry["a"], ensure_ascii=False)
        lines.append(f"  {{i:{entry['i']},q:{q_json},a:{a_json}}},")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Rebuild flashcard data from data.json.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print output to stdout instead of writing to file.",
    )
    args = parser.parse_args()

    if not DATA_JSON.exists():
        print(f"ERROR: {DATA_JSON} not found", file=sys.stderr)
        sys.exit(1)

    print(f"Reading {DATA_JSON}")
    topics = load_topics(DATA_JSON)

    total_questions = sum(len(t["q"]) for t in topics)
    for entry in topics:
        print(f"  [{entry['i']}] {entry['name']}: {len(entry['q'])} questions")

    js_source = build_js(topics)

    if args.dry_run:
        print("\n--- DRY RUN (would write to data.js) ---")
        print(js_source[:500] + "...")
    else:
        DATA_JS.write_text(js_source, "utf-8")
        print(f"\nWritten {len(js_source):,} bytes to {DATA_JS}")

    print(f"Total: {total_questions} questions across {len(topics)} topics")


if __name__ == "__main__":
    main()
