#!/usr/bin/env python3
"""Rebuild questions/data.js with embedded question + answer data from topics/ dirs.

Reads question files from questions/topics/ and corresponding answer files from
questions/topics/answers/, then generates a JavaScript file containing the
EMBEDDED_DATA array used by the flashcards application.

Usage:
    python3 rebuild.py [--dry-run]
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TOPICS_DIR = ROOT / "questions" / "topics"
ANSWERS_DIR = TOPICS_DIR / "answers"
OUTPUT_FILE = ROOT / "questions" / "data.js"

# Ordered list of topic filenames — indices match the sidebar checkboxes
TOPIC_FILES = [
    "SWE1_kvalita_kodu.txt",
    "SWE2_softwarove_inzenyrstvi.txt",
    "SWE3_databaze.txt",
    "SWE4_pocitacove_site.txt",
    "SWE5_distribuovane_systemy.txt",
    "OPS1_vyvoj_a_nasazeni.txt",
    "OPS2_bezpecna_infrastruktura.txt",
    "OPS3_cloud_computing.txt",
    "OPS4_operacni_systemy.txt",
    "OPS5_nosql_databaze.txt",
]


def read_lines(filepath: Path) -> list[str]:
    """Read non-empty lines from a text file."""
    return [
        line.strip()
        for line in filepath.read_text("utf-8").split("\n")
        if line.strip()
    ]


def load_topic(index: int, filename: str) -> dict:
    """Load questions and answers for a single topic.

    Returns a dict with keys: i (index), q (questions list), a (answers list).
    Pads missing answers with a placeholder string.
    """
    question_path = TOPICS_DIR / filename
    answer_path = ANSWERS_DIR / filename

    questions = read_lines(question_path)

    try:
        answers = read_lines(answer_path)
    except FileNotFoundError:
        print(f"  ⚠  No answers file for {filename}, using placeholders", file=sys.stderr)
        answers = ["No answer available yet."] * len(questions)

    # Warn if counts don't match
    if len(answers) < len(questions):
        diff = len(questions) - len(answers)
        print(
            f"  ⚠  {filename}: {diff} question(s) without answers, padding with placeholders",
            file=sys.stderr,
        )
        answers.extend(["No answer available yet."] * diff)
    elif len(answers) > len(questions):
        print(
            f"  ⚠  {filename}: {len(answers) - len(questions)} extra answer(s), truncating",
            file=sys.stderr,
        )

    # Ensure exact 1:1 mapping
    answers = answers[: len(questions)]

    return {"i": index, "q": questions, "a": answers}


def build_js(topics: list[dict]) -> str:
    """Generate the JavaScript source for data.js."""
    lines = [
        "// Auto-generated by rebuild.py — do not edit manually",
        "const EMBEDDED_DATA = [",
    ]

    for entry in topics:
        q_json = json.dumps(entry["q"], ensure_ascii=False)
        a_json = json.dumps(entry["a"], ensure_ascii=False)
        lines.append(f"  {{i:{entry['i']},q:{q_json},a:{a_json}}},")

    lines.append("];")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Rebuild flashcard data from topic files.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print output to stdout instead of writing to file.",
    )
    args = parser.parse_args()

    print(f"📖 Loading {len(TOPIC_FILES)} topics from {TOPICS_DIR}")

    total_questions = 0
    topics = []

    for index, filename in enumerate(TOPIC_FILES):
        topic = load_topic(index, filename)
        topics.append(topic)
        count = len(topic["q"])
        total_questions += count
        print(f"  ✓  [{index}] {filename}: {count} questions")

    js_source = build_js(topics)

    if args.dry_run:
        print("\n--- DRY RUN (would write to data.js) ---")
        print(js_source[:500] + "...")
    else:
        OUTPUT_FILE.write_text(js_source, "utf-8")
        print(f"\n✅ Written {len(js_source):,} bytes to {OUTPUT_FILE}")

    print(f"📊 Total: {total_questions} questions across {len(topics)} topics")


if __name__ == "__main__":
    main()
